# Generated by Django 4.1.7 on 2023-04-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobzilla_app', '0002_jobapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
